
--
-- ATTENDANCE_CLAIM
--
  CREATE TABLE "ATTENDANCE_CLAIM" 
   (	"CAID" NUMBER,
	"EID" NUMBER,
	"LOGIN_DATE" DATE,
	"LOGIN_TIME" TIMESTAMP(6),
	"LOGOUT_DATE" DATE,
	"LOGOUT_TIME" TIMESTAMP(6),
	"REASON" VARCHAR2(50),
	"STATUS" VARCHAR2(20),
	"COMENT" VARCHAR2(60),
	CONSTRAINT "CONSTRAINT7" PRIMARY KEY ("CAID") ENABLE
   );
--
-- EMPLOYEE
--
  CREATE TABLE "EMPLOYEE" 
   (	"EID" NUMBER(*,0),
	"FULL_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"ADDRESS" VARCHAR2(50) NOT NULL ENABLE,
	"GENDER" CHAR(1),
	"EMAIL" VARCHAR2(50),
	"PASSCODE" VARCHAR2(30),
	"CONTACT" LONG,
	PRIMARY KEY ("EID") ENABLE,
	CONSTRAINT "EMPLOYEE_UK1" UNIQUE ("EMAIL") ENABLE
   );
--
-- ATTENDANCE
--
  CREATE TABLE "ATTENDANCE" 
   (	"AID" NUMBER(*,0),
	"EID" NUMBER(*,0),
	"ATTEND_DATE" DATE,
	"LOGIN_TIME" TIMESTAMP(6),
	"LOGOUT_TIME" TIMESTAMP(6),
	"SHIFT" VARCHAR2(15),
	"TOTAL_TIME" TIMESTAMP(6),
	"LOGOUT_DATE" TIMESTAMP(6),
	PRIMARY KEY ("AID") ENABLE
   );
--
-- EMPLOYEE_POST
--
  CREATE TABLE "EMPLOYEE_POST" 
   (	"EPOID" NUMBER(*,0),
	"EID" NUMBER(*,0),
	"POST" VARCHAR2(20),
	PRIMARY KEY ("EPOID") ENABLE
   );
--
-- HOLIDAY_LIST
--
  CREATE TABLE "HOLIDAY_LIST" 
   (	"HID" NUMBER(*,0),
	"H_DATE" DATE,
	"OCCATION" VARCHAR2(30),
	PRIMARY KEY ("HID") ENABLE
   );
--
-- LEAVE
--
  CREATE TABLE "LEAVE" 
   (	"LID" NUMBER(*,0),
	"EID" NUMBER(*,0),
	"LEAVE_TYPE" VARCHAR2(15),
	"FROM_DATE" DATE,
	"TO_DATE" DATE,
	"DAYS" NUMBER(*,0),
	"REASON" VARCHAR2(150),
	"STATUS" VARCHAR2(20),
	"REQUESTED_FROM" DATE,
	"REQUESTED_TO" DATE,
	"COMENT" VARCHAR2(150),
	PRIMARY KEY ("LID") ENABLE
   );
--
-- LEAVEDAYS
--
  CREATE TABLE "LEAVEDAYS" 
   (	"LDID" NUMBER,
	"EID" NUMBER,
	"LEAVETYPE" VARCHAR2(20),
	"DAYS" NUMBER,
	CONSTRAINT "CONSTRAINT10" PRIMARY KEY ("LDID") ENABLE
   );
--
-- LEAVES_TYPES
--
  CREATE TABLE "LEAVES_TYPES" 
   (	"LTID" NUMBER,
	"LEAVE_NAME" VARCHAR2(20),
	"DAYS_OFF" NUMBER,
	CONSTRAINT "CONSTRAINT9" PRIMARY KEY ("LTID") ENABLE
   );
--
-- MONTHLY_STATEMENT
--
  CREATE TABLE "MONTHLY_STATEMENT" 
   (	"MON_REC_ID" NUMBER,
	"EID" NUMBER,
	"MONTH" VARCHAR2(20),
	"TOTALLEAVEDAYS" NUMBER,
	"TOTALWORKINGHRS" NUMBER,
	"TOTALNIGHTSHIFTS" NUMBER,
	"TOTALWOH" NUMBER,
	"TOTALWOSH" NUMBER,
	"TOTALMEALALLOW" NUMBER,
	CONSTRAINT "CONSTRAINT6" PRIMARY KEY ("MON_REC_ID") ENABLE
   );
--
-- PAYOUT
--
  CREATE TABLE "PAYOUT" 
   (	"PID" NUMBER(*,0),
	"EID" NUMBER(*,0),
	"PAY_MONTH" VARCHAR2(10),
	"WOH_DAY" NUMBER(*,0),
	"NIGHT" NUMBER(*,0),
	"TOTAL_SALARY" NUMBER,
	"LEAVE_DAYS" NUMBER(*,0),
	"WORKING_HOUR" NUMBER,
	"MEALALLOWANCE" NUMBER,
	"WOSH_DAY" NUMBER,
	PRIMARY KEY ("PID") ENABLE
   );
--
-- POST_LIST
--
  CREATE TABLE "POST_LIST" 
   (	"POST" VARCHAR2(20),
	"BASIC_SALARY" NUMBER,
	"POID" NUMBER,
	CONSTRAINT "CONSTRAINT1" PRIMARY KEY ("POID") ENABLE,
	CONSTRAINT "CONSTRAINT2" UNIQUE ("POST") ENABLE
   );
--
-- ALLOWANCE
--
  CREATE TABLE "ALLOWANCE" 
   (	"POST" VARCHAR2(20),
	"WOH" NUMBER,
	"WONS" NUMBER,
	"MEAL_ALLOWANCE" NUMBER,
	"AID" NUMBER(*,0),
	"WOSH" NUMBER,
	PRIMARY KEY ("AID") ENABLE
   );
--
-- REPORTTOSUPERVISOR
--
  CREATE TABLE "REPORTTOSUPERVISOR" 
   (	"RTSID" NUMBER,
	"SUPERVISOR" VARCHAR2(60),
	"MESSAGE" VARCHAR2(200),
	"EMAIL" VARCHAR2(60),
	CONSTRAINT "CONSTRAINT13" PRIMARY KEY ("RTSID") ENABLE
   );
--
-- ROLES
--
  CREATE TABLE "ROLES" 
   (	"ROLEID" NUMBER(*,0),
	"ROLENAME" VARCHAR2(30),
	PRIMARY KEY ("ROLEID") ENABLE
   );
--
-- SUPERVISOR
--
  CREATE TABLE "SUPERVISOR" 
   (	"EID" NUMBER,
	"SUPERVISOR1" VARCHAR2(60),
	"SUPERVISOR2" VARCHAR2(60),
	"SUPERVISOR3" VARCHAR2(60),
	"SUPERVISOR4" VARCHAR2(60),
	"SUPERVISOR5" VARCHAR2(60),
	CONSTRAINT "CONSTRAINT12" PRIMARY KEY ("EID") ENABLE
   );
--
-- USERROLES
--
  CREATE TABLE "USERROLES" 
   (	"USERROLESID" NUMBER(*,0),
	"ROLEID" NUMBER(*,0),
	"EID" NUMBER(*,0),
	PRIMARY KEY ("USERROLESID") ENABLE
   );
--
-- WORK_IN_OUT
--
  CREATE TABLE "WORK_IN_OUT" 
   (	"IN_OUT_ID" NUMBER(*,0),
	"EID" NUMBER(*,0),
	"OUT_ON_WORK" TIMESTAMP(6),
	"RETURN_INSIDE" TIMESTAMP(6),
	"REASON" LONG,
	PRIMARY KEY ("IN_OUT_ID") ENABLE
   );
--
-- CONSTRAINT2
--
  CREATE UNIQUE INDEX "CONSTRAINT2" ON "POST_LIST" ("POST");
--
-- EMPLOYEE_UK1
--
  CREATE UNIQUE INDEX "EMPLOYEE_UK1" ON "EMPLOYEE" ("EMAIL");
--
-- CONSTRAINT4
--
ALTER TABLE "ALLOWANCE" ADD CONSTRAINT "CONSTRAINT4" FOREIGN KEY ("POST") REFERENCES "POST_LIST"("POST") ENABLE;

--
-- SYS_C0010811
--
ALTER TABLE "ATTENDANCE" ADD  FOREIGN KEY ("EID") REFERENCES "EMPLOYEE"("EID") ENABLE;

--
-- CONSTRAINT8
--
ALTER TABLE "ATTENDANCE_CLAIM" ADD CONSTRAINT "CONSTRAINT8" FOREIGN KEY ("EID") REFERENCES "EMPLOYEE"("EID") ENABLE;

--
-- CONSTRAINT5
--
ALTER TABLE "EMPLOYEE_POST" ADD CONSTRAINT "CONSTRAINT5" FOREIGN KEY ("POST") REFERENCES "POST_LIST"("POST") ENABLE;

--
-- SYS_C0010806
--
ALTER TABLE "EMPLOYEE_POST" ADD  FOREIGN KEY ("EID") REFERENCES "EMPLOYEE"("EID") ENABLE;

--
-- SYS_C0010809
--
ALTER TABLE "LEAVE" ADD  FOREIGN KEY ("EID") REFERENCES "EMPLOYEE"("EID") ENABLE;

--
-- CONSTRAINT11
--
ALTER TABLE "LEAVEDAYS" ADD CONSTRAINT "CONSTRAINT11" FOREIGN KEY ("EID") REFERENCES "EMPLOYEE"("EID") ENABLE;

--
-- CONSTRAINT3
--
ALTER TABLE "MONTHLY_STATEMENT" ADD CONSTRAINT "CONSTRAINT3" FOREIGN KEY ("EID") REFERENCES "EMPLOYEE"("EID") ENABLE;

--
-- SYS_C0010817
--
ALTER TABLE "PAYOUT" ADD  FOREIGN KEY ("EID") REFERENCES "EMPLOYEE"("EID") ENABLE;

--
-- CONSTRAINT14
--
ALTER TABLE "REPORTTOSUPERVISOR" ADD CONSTRAINT "CONSTRAINT14" FOREIGN KEY ("EMAIL") REFERENCES "EMPLOYEE"("EMAIL") ENABLE;

--
-- SYS_C0010820
--
ALTER TABLE "USERROLES" ADD  FOREIGN KEY ("ROLEID") REFERENCES "ROLES"("ROLEID") ENABLE;

--
-- SYS_C0010821
--
ALTER TABLE "USERROLES" ADD  FOREIGN KEY ("EID") REFERENCES "EMPLOYEE"("EID") ENABLE;

--
-- SYS_C0010813
--
ALTER TABLE "WORK_IN_OUT" ADD  FOREIGN KEY ("EID") REFERENCES "EMPLOYEE"("EID") ENABLE;

