
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Attendance.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
public partial class ALLOWANCE
{

    [Required(ErrorMessage = "*")]
    [Display(Name = "Post")]
    public string POST { get; set; }
    [Required(ErrorMessage = "*")]
    [Display(Name = "Work on WeekEnd")]
    public Nullable<decimal> WOH { get; set; }
    [Display(Name = "Work on Night Shift")]
    [Required(ErrorMessage = "*")]
    public Nullable<decimal> WONS { get; set; }
    [Required(ErrorMessage = "*")]
    [Display(Name = "Meal Allowance")]
    public Nullable<decimal> MEAL_ALLOWANCE { get; set; }
    [Required(ErrorMessage = "*")]
    public decimal AID { get; set; }
    [Required(ErrorMessage = "*")]
    [Display(Name = "Work on Holiday")]
    public Nullable<decimal> WOSH { get; set; }

}

}
