
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Attendance.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
public partial class LEAVES_TYPES
{
     [Display(Name = "Leave Type Id")]
    public decimal LTID { get; set; }
    [Required(ErrorMessage = "*")]
    public string LEAVE_NAME { get; set; }
    [Required(ErrorMessage = "*")]
    [Display(Name = "Maximum Days")]
    public Nullable<decimal> DAYS_OFF { get; set; }

}

}
