
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Attendance.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
public partial class PAYOUT
{

    [Display(Name = "Payout Id")]
    public decimal PID { get; set; }

    [Display(Name = "Employee Id")]
    public Nullable<decimal> EID { get; set; }

    [Display(Name = "Month")]
    public string PAY_MONTH { get; set; }

    [Display(Name = "Work on Weekend")]
    public Nullable<decimal> WOH_DAY { get; set; }

    [Display(Name = "Work on Night shift")]
    public Nullable<decimal> NIGHT { get; set; }

    [Display(Name = "Total Salary")]
    public Nullable<decimal> TOTAL_SALARY { get; set; }

    [Display(Name = "Leave days")]
    public Nullable<decimal> LEAVE_DAYS { get; set; }

    [Display(Name = "Working Hours")]
    public Nullable<decimal> WORKING_HOUR { get; set; }

    [Display(Name = "Number of Meal Allowance")]
    public Nullable<decimal> MEALALLOWANCE { get; set; }

    [Display(Name = "Work on Holiday")]
    public Nullable<decimal> WOSH_DAY { get; set; }



    public virtual EMPLOYEE EMPLOYEE { get; set; }

}

}
