
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Attendance.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
public partial class SUPERVISOR
{

    public decimal EID { get; set; }
    [Required(ErrorMessage = "*")]
    public string SUPERVISOR1 { get; set; }

    public string SUPERVISOR2 { get; set; }

    public string SUPERVISOR3 { get; set; }

    public string SUPERVISOR4 { get; set; }

    public string SUPERVISOR5 { get; set; }



    public virtual EMPLOYEE EMPLOYEE { get; set; }

}

}
