
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Attendance.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
public partial class LEAVE
{

    public decimal LID { get; set; }

    public Nullable<decimal> EID { get; set; }
    [Required]
    public string LEAVE_TYPE { get; set; }    
   
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
    public Nullable<System.DateTime> FROM_DATE { get; set; }
    
   
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
    public Nullable<System.DateTime> TO_DATE { get; set; }

    public Nullable<decimal> DAYS { get; set; }

    public string Name { get; set; }
    public string REASON { get; set; }

    public string STATUS { get; set; }



    public virtual EMPLOYEE EMPLOYEE { get; set; }

}

}
