
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Attendance.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LEAVEDAY
{

    public decimal LDID { get; set; }

    public Nullable<decimal> EID { get; set; }

    public string LEAVETYPE { get; set; }

    public Nullable<decimal> DAYS { get; set; }



    public virtual EMPLOYEE EMPLOYEE { get; set; }

}

}
