
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Attendance.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
public partial class POST_LIST
{
    [Required(ErrorMessage = "*")]
    [Display(Name = "Post")]
    public string POST { get; set; }
    
    [Display(Name = "Basic salary")]
    public Nullable<decimal> BASIC_SALARY { get; set; }
       
    public decimal POID { get; set; }

}

}
