
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Attendance.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MONTHLY_STATEMENT
{

    public decimal MON_REC_ID { get; set; }

    public Nullable<decimal> EID { get; set; }

    public string MONTH { get; set; }

    public Nullable<decimal> TOTALLEAVEDAYS { get; set; }

    public Nullable<decimal> TOTALWORKINGHRS { get; set; }

    public Nullable<decimal> TOTALNIGHTSHIFTS { get; set; }

    public Nullable<decimal> TOTALWOH { get; set; }



    public virtual EMPLOYEE EMPLOYEE { get; set; }

}

}
